/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package manager;

import java.sql.*;
import Conexao.ConexaoBD;
import java.awt.HeadlessException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class CadCafes extends javax.swing.JFrame {

    Connection conexao = ConexaoBD.conector();
    PreparedStatement pst;
    ResultSet rs;

    /**
     * Creates new form CadCafes
     */
    public CadCafes() {
        conexao = ConexaoBD.conector();
        System.out.println(conexao);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        voltar = new javax.swing.JButton();
        nomeespaco = new javax.swing.JTextField();
        lotacaoespaco = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Cadastro de espaços de café");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        voltar.setBorder(null);
        voltar.setContentAreaFilled(false);
        voltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        getContentPane().add(voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 50, 40, 20));

        nomeespaco.setBackground(new java.awt.Color(226, 137, 171));
        nomeespaco.setBorder(null);
        getContentPane().add(nomeespaco, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 159, 182, 16));

        lotacaoespaco.setBackground(new java.awt.Color(226, 137, 171));
        lotacaoespaco.setBorder(null);
        getContentPane().add(lotacaoespaco, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 222, 180, -1));

        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 304, 90, 27));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cadastrarcafe.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            CCafes();        // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(CadCafes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        TelaInicial inicio = new TelaInicial();
        inicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_voltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadCafes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CadCafes().setVisible(true);
        });
    }

    public void CCafes() throws SQLException {
        String sql2 = "SELECT count( idcafes) as total FROM tbcafes;";
        pst = conexao.prepareStatement(sql2);
        rs = pst.executeQuery();

        if (rs.next()) {
            int qtde = rs.getInt(1);
            System.out.println(qtde);
            if (qtde <= 2) {

                String sql = "insert into tbcafes (nomeespaco, lotacaocafe)VALUES (?,?)";
                try {
                    conexao.setAutoCommit(false);
                    pst = conexao.prepareStatement(sql);

                    pst.setString(1, nomeespaco.getText());
                    pst.setString(2, lotacaoespaco.getText());
                    if ((nomeespaco.getText().isEmpty()) || (nomeespaco.getText().isEmpty())) {
                        JOptionPane.showMessageDialog(null, "Preencha todos os campos ", "Aviso!", JOptionPane.INFORMATION_MESSAGE);
                    } else {

                        int adicionado = pst.executeUpdate();
                        if (adicionado > 0) {

                            nomeespaco.setText(null);
                            lotacaoespaco.setText(null);
                            JOptionPane.showMessageDialog(null, "Espaço cadastrado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                        }

                    }
                    conexao.commit();
                } catch (HeadlessException | SQLException e) {
                    JOptionPane.showMessageDialog(null, "A lotação aceita apenas números");
                    nomeespaco.setText(null);
                    lotacaoespaco.setText(null);
                }
            
        } else {
            JOptionPane.showMessageDialog(null, "Número máximo de espaços cadastrados");
            nomeespaco.setText(null);
            lotacaoespaco.setText(null);
        }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField lotacaoespaco;
    private javax.swing.JTextField nomeespaco;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
