/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package manager;

import java.sql.*;
import Conexao.ConexaoBD;
import java.awt.HeadlessException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class CadSalas extends javax.swing.JFrame {

    Connection conexao = ConexaoBD.conector();
    PreparedStatement pst;
    ResultSet rs;

    /**
     * Creates new form CadSalas
     */
    public CadSalas() {
        conexao = ConexaoBD.conector();
        System.out.println(conexao);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomesala = new javax.swing.JTextField();
        lotacaosala = new javax.swing.JTextField();
        cadastrar = new javax.swing.JButton();
        voltar = new javax.swing.JButton();
        fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Cadastro de salas");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nomesala.setBackground(new java.awt.Color(226, 137, 171));
        nomesala.setBorder(null);
        getContentPane().add(nomesala, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 160, 180, -1));

        lotacaosala.setBackground(new java.awt.Color(226, 137, 171));
        lotacaosala.setBorder(null);
        getContentPane().add(lotacaosala, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 222, 180, -1));

        cadastrar.setBorder(null);
        cadastrar.setContentAreaFilled(false);
        cadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(cadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 301, 91, 30));

        voltar.setBorder(null);
        voltar.setContentAreaFilled(false);
        voltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        getContentPane().add(voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 50, 40, 20));

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cadastrarsala.png"))); // NOI18N
        getContentPane().add(fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 582, 396));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarActionPerformed
        try {
            CSala();        // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(CadSalas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cadastrarActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        TelaInicial inicio = new TelaInicial();
        inicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_voltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadSalas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CadSalas().setVisible(true);
        });
    }

    public void CSala() throws SQLException {
        String sql2 = "SELECT count( idsala) as total FROM tbsalas;";
        pst = conexao.prepareStatement(sql2);
        rs = pst.executeQuery();

        if (rs.next()) {
            int qtde = rs.getInt(1);
            System.out.println(qtde);
            if (qtde <= 3) {

                String sql = "insert into tbsalas (nomesala, lotacaosala)VALUES (?,?)";
                try {
                    conexao.setAutoCommit(false);
                    pst = conexao.prepareStatement(sql);

                    pst.setString(1, nomesala.getText());
                    pst.setString(2, lotacaosala.getText());
                    if ((nomesala.getText().isEmpty()) || (nomesala.getText().isEmpty())) {
                        JOptionPane.showMessageDialog(null, "Preencha todos os campos ", "Aviso!", JOptionPane.INFORMATION_MESSAGE);
                    } else {

                        int adicionado = pst.executeUpdate();
                        if (adicionado > 0) {

                            nomesala.setText(null);
                            lotacaosala.setText(null);
                            JOptionPane.showMessageDialog(null, "Sala cadastrada com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                        }

                    }
                    conexao.commit();
                } catch (HeadlessException | SQLException e) {
                    JOptionPane.showMessageDialog(null, "A lotação aceita apenas números");
                    nomesala.setText(null);
                    lotacaosala.setText(null);
                }

            } else {
                JOptionPane.showMessageDialog(null, "Número máximo de salas cadastradas");
                nomesala.setText(null);
                lotacaosala.setText(null);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrar;
    private javax.swing.JLabel fundo;
    private javax.swing.JTextField lotacaosala;
    private javax.swing.JTextField nomesala;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
