/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package manager;

import Conexao.ConexaoBD;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Usuario
 */
public class ConsultaPart extends javax.swing.JFrame {

    Connection conexao = ConexaoBD.conector();
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form ConsultaPart
     */
    public ConsultaPart() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelapart = new javax.swing.JTable();
        pesquisar = new javax.swing.JTextField();
        boxpesquisa = new javax.swing.JComboBox<>();
        voltar = new javax.swing.JButton();
        fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Consulta de participantes");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelapart.setBackground(new java.awt.Color(255, 237, 237));
        tabelapart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelapart.setGridColor(new java.awt.Color(235, 108, 142));
        tabelapart.setSelectionBackground(new java.awt.Color(235, 108, 142));
        jScrollPane1.setViewportView(tabelapart);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 513, 130));

        pesquisar.setBackground(new java.awt.Color(226, 137, 171));
        pesquisar.setForeground(new java.awt.Color(255, 255, 255));
        pesquisar.setBorder(null);
        pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarActionPerformed(evt);
            }
        });
        pesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pesquisarKeyReleased(evt);
            }
        });
        getContentPane().add(pesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 130, 137, 16));

        boxpesquisa.setBackground(new java.awt.Color(226, 137, 171));
        boxpesquisa.setForeground(new java.awt.Color(255, 255, 255));
        boxpesquisa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pesquisar por", "ID", "Nome", "Sobrenome" }));
        boxpesquisa.setBorder(null);
        getContentPane().add(boxpesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 120, 30));

        voltar.setBorder(null);
        voltar.setContentAreaFilled(false);
        voltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        getContentPane().add(voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 40, 40, 30));

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Design sem nome (5).png"))); // NOI18N
        getContentPane().add(fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 380));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesquisarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        mostrar();        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void pesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pesquisarKeyReleased
        Consulta();        // TODO add your handling code here:
    }//GEN-LAST:event_pesquisarKeyReleased

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        TelaInicial inicio = new TelaInicial();
        inicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_voltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaPart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ConsultaPart().setVisible(true);
        });
    }

    private void Consulta() {
        try {
            int pesquisa = boxpesquisa.getSelectedIndex();
            System.out.println(boxpesquisa.getSelectedIndex());
            switch (pesquisa) {
                case 1: {
                    String sql = " select idparticipante 'ID' , nomeparticipante 'Nome', sobrenomeparticipante 'Sobrenome',nomesala '1ª sala', nomesala '2ª sala', nomeespaco '1º café', nomeespaco '2º café' from tbparticipantes inner join tbsalas on idsala=fksala1 inner join tbcafes on idcafes=fkcafe1 where idparticipante like ?";
                    pst = conexao.prepareStatement(sql);
                    pst.setString(1, pesquisar.getText() + "%");
                    rs = pst.executeQuery();
                    tabelapart.setModel(DbUtils.resultSetToTableModel(rs));
                    break;
                }
                case 2: {
                    String sql = " select idparticipante 'ID' , nomeparticipante 'Nome', sobrenomeparticipante 'Sobrenome',nomesala '1ª sala', nomesala '2ª sala', nomeespaco '1º café', nomeespaco '2º café' from tbparticipantes inner join tbsalas on idsala=fksala1 inner join tbcafes on idcafes=fkcafe1 where nomeparticipante like ?";
                    pst = conexao.prepareStatement(sql);
                    pst.setString(1, pesquisar.getText() + "%");
                    rs = pst.executeQuery();
                    tabelapart.setModel(DbUtils.resultSetToTableModel(rs));
                    break;
                }
                case 3: {
                    String sql = " select idparticipante 'ID' , nomeparticipante 'Nome', sobrenomeparticipante 'Sobrenome',nomesala '1ª sala', nomesala '2ª sala', nomeespaco '1º café', nomeespaco '2º café' from tbparticipantes inner join tbsalas on idsala=fksala1 inner join tbcafes on idcafes=fkcafe1 where sobrenomeparticipante like ?";
                    pst = conexao.prepareStatement(sql);
                    pst.setString(1, pesquisar.getText() + "%");
                    rs = pst.executeQuery();
                    tabelapart.setModel(DbUtils.resultSetToTableModel(rs));
                    break;
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void mostrar() {
        String sql = "select idparticipante 'ID' , nomeparticipante 'Nome', sobrenomeparticipante 'Sobrenome',nomesala '1ª sala', nomesala '2ª sala', \n"
                + "nomeespaco '1º café', nomeespaco '2º café' from tbparticipantes\n"
                + "inner join tbsalas on idsala=fksala1 \n"
                + " inner join tbcafes on idcafes=fkcafe1; ";
        try {
            pst = conexao.prepareStatement(sql);
            rs = pst.executeQuery();
            tabelapart.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxpesquisa;
    private javax.swing.JLabel fundo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField pesquisar;
    private javax.swing.JTable tabelapart;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
