/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package manager;

import java.sql.*;

/**
 *
 * @author Usuario
 */
public class TelaInicial extends javax.swing.JFrame {

    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cadpart = new javax.swing.JButton();
        cadsala = new javax.swing.JButton();
        cadcafe = new javax.swing.JButton();
        consultpart = new javax.swing.JButton();
        consultsala = new javax.swing.JButton();
        consultcafe = new javax.swing.JButton();
        fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Início");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cadpart.setBorder(null);
        cadpart.setContentAreaFilled(false);
        cadpart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cadpart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadpartActionPerformed(evt);
            }
        });
        getContentPane().add(cadpart, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 190, 130));

        cadsala.setBorder(null);
        cadsala.setContentAreaFilled(false);
        cadsala.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cadsala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadsalaActionPerformed(evt);
            }
        });
        getContentPane().add(cadsala, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 190, 140));

        cadcafe.setBorder(null);
        cadcafe.setContentAreaFilled(false);
        cadcafe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cadcafe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadcafeActionPerformed(evt);
            }
        });
        getContentPane().add(cadcafe, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 210, 170, 140));

        consultpart.setBorder(null);
        consultpart.setContentAreaFilled(false);
        consultpart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        consultpart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultpartActionPerformed(evt);
            }
        });
        getContentPane().add(consultpart, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 180, 150));

        consultsala.setBorder(null);
        consultsala.setContentAreaFilled(false);
        consultsala.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        consultsala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultsalaActionPerformed(evt);
            }
        });
        getContentPane().add(consultsala, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 401, 210, 150));

        consultcafe.setBorder(null);
        consultcafe.setContentAreaFilled(false);
        consultcafe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        consultcafe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultcafeActionPerformed(evt);
            }
        });
        getContentPane().add(consultcafe, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 401, 180, 150));

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fundo.png"))); // NOI18N
        fundo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        fundo.setPreferredSize(new java.awt.Dimension(1041, 520));
        getContentPane().add(fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 610));

        setSize(new java.awt.Dimension(1056, 651));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cadsalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadsalaActionPerformed
        CadSalas cadsalas = new CadSalas();
        cadsalas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cadsalaActionPerformed

    private void cadpartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadpartActionPerformed
        CadParticipantes cadparti = new CadParticipantes();
        cadparti.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cadpartActionPerformed

    private void cadcafeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadcafeActionPerformed
        CadCafes cadcafes = new CadCafes();
        cadcafes.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_cadcafeActionPerformed

    private void consultpartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultpartActionPerformed
        ConsultaPart consulpart = new ConsultaPart();
        consulpart.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_consultpartActionPerformed

    private void consultsalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultsalaActionPerformed
        ConsultaSalas consulsala = new ConsultaSalas();
        consulsala.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_consultsalaActionPerformed

    private void consultcafeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultcafeActionPerformed
        ConsultaCafes consulcafe = new ConsultaCafes();
        consulcafe.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_consultcafeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaInicial().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadcafe;
    private javax.swing.JButton cadpart;
    private javax.swing.JButton cadsala;
    private javax.swing.JButton consultcafe;
    private javax.swing.JButton consultpart;
    private javax.swing.JButton consultsala;
    private javax.swing.JLabel fundo;
    // End of variables declaration//GEN-END:variables
}
